config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :lists, only: [:new, :create, :edit, :show, :destroy, :update]
  end # poprzez podanie resources konfiguruje automatycznie ścieżki, only po aby robić po kolei, bo inaczej stworzy caly komplet

  resources :lists, only: [] do
    resources :tickets, only: [:new, :create, :edit, :update]
  end 

  resources :sessions, only: [:new, :create, :destroy]
  resources :registrations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists
  
  has_many :users, through: :members
  has_many :members, dependent: :destroy

  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tickets
  
  validates :title, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  enum status: {
    bug: 10,
    improvement: 20,
    story: 30,
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :boards, through: :members, dependent: :destroy
  has_many :members, dependent: :destroy

  validates :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user

  def authenticate_user
    if current_user.blank?
      redirect_to new_session_path, alert: 'Please log in first!'
    end
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # before_action :find_board, only: [:update, :destroy, :show, :edit] # callback, wywoła się przed akcjami w only: ...

  def index
    @own_boards = current_user.boards.where(owner_id: current_user.id)
    @member_boards = current_user.boards.where.not(owner_id: current_user.id)
  end

  def new
    @board = Board.new
  end

  def create
    service = BoardCreator.new(board_params.merge!(owner_id: current_user.id))
    if service.save
      redirect_to boards_path
    else
      @board = service.board
      render :new
    end
  end

  def edit
    board
  end

  def update
    if board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    board.destroy
    redirect_to boards_path, notice: 'Board deleted'
  end

  def show
    board
  end

  private

  # mozna tej metody uzyc do before_action
  # def find_board
  #   @board = Board.find(params[:id])
  # end

  def board
    @board ||= Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = board.lists.new
  end

  def create
    @list = board.lists.new(list_params)
    if @list.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def edit
    list
  end

  def update
    if list.update(list_params)
      redirect_to board_path(board)
    else
      render :edit
    end
  end 

  def show
    list
  end

  def destroy
    list.destroy
    redirect_to board_path(board)
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end

  def list
    @list ||= board.lists.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user

  def new
  end

  def create
    service = RegistrationForm.new(registration_params)
    if service.save
      redirect_to new_session_path, notice: 'Successfully signed up please log in!'
    else
      redirect_to new_registration_path, alert: service.errors.full_messages.join(', ')
    end
  end

  private

  def registration_params
    params.permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user
  before_action :redirect_to_root_when_logged_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to boards_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to boards_path, notice: 'Logout!'
  end

  private

  def redirect_to_root_when_logged_in
    if current_user.present?
      redirect_to boards_path, alert: 'You are already signed in!'
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @ticket = list.tickets.new
  end

  def create
    @ticket = list.tickets.new(ticket_params)
    if @ticket.save
      redirect_to board_list_path(list.board, list), notice: 'Ticket was successfully created!'
    else
      render :new
    end
  end

  def edit
    ticket
  end

  def update
    if ticket.update(ticket_params)
      redirect_to board_list_path(list.board, list)
    else
      render :new
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :status)
  end

  def list
    @list ||= List.find(params[:list_id])
  end

  def ticket
    @ticket ||= list.tickets.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
  <%= render partial: './shared/errors', locals: { object: @board } %>

  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Boards</h1>
<%= link_to 'New Board', new_board_path %>
<!-- zamiast stringa jest metoda, że przekierowuje do danej ścieżki - patrzeć przez rake routes -->
<h3>Own Boards</h3>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    <%- @own_boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.created_at %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Show', board_path(board) %></td>
        <td><%= link_to 'Delete', board_path(board), method: :delete, data: { confirm: 'Ary you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Member Boards</h3>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    <%- @member_boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.created_at %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Show', board_path(board) %></td>
        <td><%= link_to 'Delete', board_path(board), method: :delete, data: { confirm: 'Ary you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<h1>Board nr: <%= @board.id %> Lists </h1>
<br>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    <%- @board.lists.each do |list| %>
      <tr>
        <td><%= list.id %></td>
        <td><%= list.title %></td>
        <td><%= list.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_board_list_path(@board, list) %>
          <%= link_to 'Delete', board_list_path(@board, list), method: :delete, data: { confirm: "Are you sure?"} %>
          <%= link_to 'Show', board_list_path(@board, list) %>
        </td>

      </tr>
    <% end %>
  </tbody>
  <%= link_to 'Back to Boards', boards_path %>
</table>

<%= link_to "Add list", new_board_list_path(@board) %> </br>
<%= @lists %>
<%= link_to 'Back', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trolo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: './shared/navbar' %>
    <%= render partial: './shared/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for [@board, @list] do |f| %>
  <%= render partial: './shared/errors', locals: { object: @list } %>

  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List <%= @list.id %></h1>
<%= render 'form' %>

<%= link_to 'Back', "/boards/#{@board.id}" %>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= render 'form' %>

app/views/lists/show.html.erb
<h1>List nr: <%= @list.id %> Tickets </h1>

<br>  
<%= link_to "Back to Lists", board_path(@board) %> 
<br>
<br>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Status</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    <%- @list.tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.id %></td>
        <td><%= ticket.title %></td>
        <td><%= ticket.status %></td>        
        <td><%= ticket.created_at %></td>
        <td><%= link_to 'Edit', edit_list_ticket_path(@list, ticket) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>  
<%= link_to "Add ticket", new_list_ticket_path(@list) %>
<br>
<%= link_to "Back", board_path(@board) %> 

app/views/shared/_alerts.html.erb
<% if notice.present? %>
  <p>NOTICE: <%= notice %></p>
<% end %>
<% if alert.present? %>
  <p>Alert: <%= alert %></p>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.present? %>
  <ul>
    <%- object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<div class='ala-nav'>
  <% if current_user.present? %>
    <%= link_to 'Sign Out', session_path(current_user), method: :delete %>
  <% else %>
    <%= link_to 'Sign up', new_registration_path %>
  <% end %>     
</div>

app/views/tickets/_form.html.erb
<%= form_for [@list, @ticket] do |f| %>
  <%= render partial: './shared/errors', locals: { object: @ticket } %>

  <%= f.text_field :title %>

  <%= 'Status:'%> 
  <%= f.select :status, Ticket.statuses.map { |key, val| [key.capitalize, key] } %>
  
  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Edit Ticket <%= @ticket.id %></h1>
<%= render 'form' %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>
<%= render 'form' %>